public enum CombatAiPersonalityKind
{
    Neutral = 0,
    AttentionSeeker = 1,
    BattleJunkie = 2,
    Calm = 3,
    Cautious = 4,
    Clumsy = 5,
    Coward = 6,
    Cunning = 7,
    Despicable = 8,
    Devoted = 9,
    Eccentric = 10,
    Gossiper = 11,
    HotBlooded = 12,
    Innocent = 13,
    Lazy = 14,
    Lecherous = 15,
    Lonely = 16,
    LoneWolf = 17,
    OverlySerious = 18,
    Reckless = 19,
    Unstable = 20,
}
