public enum SkillId
{
    None = 0,
    Sword_Slash = 1,
    Bible_StrBuff = 2,
    Wand_Bolt = 3,
    Grimoire_StrDebuff = 4,
    Bible_FaiBuff = 6,
    Bible_IntBuff = 7,
    Bible_AgiBuff = 8,
    StatDebuff_INT = 9,
    StatDebuff_FAI = 10,
    StatDebuff_AGI = 11,
    Shield_Slash = 12,
    Grimoire_Bolt = 13,
    Bible_Smite = 14,
    Rosary_Strike = 15,
    Rosary_DistantHeal = 16,
    Rosary_CloseHeal = 17,
    Wand_ArcaneBlast = 18,
}
